// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATV4l_ls8gCy1sKmzpFsbtcFvCCHJOhDo',
    appId: '1:672457909931:web:82a9f48cd68faa982ab9ee',
    messagingSenderId: '672457909931',
    projectId: 'iranalytics-3142e',
    authDomain: 'iranalytics-3142e.firebaseapp.com',
    storageBucket: 'iranalytics-3142e.firebasestorage.app',
    measurementId: 'G-GBKJS70PF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGhe0RSecu5S1xRBtRfGOLH1OBjiZKZ7c',
    appId: '1:672457909931:android:52812928ae40fb412ab9ee',
    messagingSenderId: '672457909931',
    projectId: 'iranalytics-3142e',
    storageBucket: 'iranalytics-3142e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgCu4-BQrtz1O5IW6LxLOdCXUJHQmksGw',
    appId: '1:672457909931:ios:f99d6f0392dbf64f2ab9ee',
    messagingSenderId: '672457909931',
    projectId: 'iranalytics-3142e',
    storageBucket: 'iranalytics-3142e.firebasestorage.app',
    iosBundleId: 'com.iranalytics.iranalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgCu4-BQrtz1O5IW6LxLOdCXUJHQmksGw',
    appId: '1:672457909931:ios:f99d6f0392dbf64f2ab9ee',
    messagingSenderId: '672457909931',
    projectId: 'iranalytics-3142e',
    storageBucket: 'iranalytics-3142e.firebasestorage.app',
    iosBundleId: 'com.iranalytics.iranalytics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATV4l_ls8gCy1sKmzpFsbtcFvCCHJOhDo',
    appId: '1:672457909931:web:37b9f924cba4f37a2ab9ee',
    messagingSenderId: '672457909931',
    projectId: 'iranalytics-3142e',
    authDomain: 'iranalytics-3142e.firebaseapp.com',
    storageBucket: 'iranalytics-3142e.firebasestorage.app',
    measurementId: 'G-YC6FVWSTF9',
  );

}